apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-google-search.fullname" . }}
  labels:
    {{- include "mcp-google-search.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcp-google-search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mcp-google-search.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-google-search.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: port
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: log_level
            - name: MAX_RESULTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: max_results
            - name: RATE_LIMIT_PER_MIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: rate_limit_per_min
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: google_api_key
            - name: GOOGLE_SEARCH_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-google-search.fullname" . }}
                  key: google_search_id
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}