apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-google-search.fullname" . }}
  labels:
    {{- include "mcp-google-search.labels" . | nindent 4 }}
type: Opaque
data:
  google_api_key: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  google_search_id: {{ .Values.secrets.googleSearchId | b64enc | quote }}